services:
  app:
    image: ghcr.io/jimwitte/baserow-record-linker:latest
    restart: no
    env_file:
      - .env
    environment:
      - BASEROW_URL
      - BASEROW_API_TOKEN
      - CONFIG_TABLE_ID
    networks:
      - web
networks:
  web:
    ipam:
      config:
        - subnet: 192.168.201.0/24
